export const ACTION_TYPES = {
    SET_PLAYING_FILMS: 'SET_PLAYING_FILMS',
    SET_PLAYING_SHOWS: 'SET_PLAYING_SHOWS',
    SET_NEXT_EPISODE_TO_AIR: 'SET_NEXT_EPISODE_TO_AIR',
    GET_CONTENT: 'GET_CONTENT',
    SEARCH_INFO: 'SEARCH_INFO',
};